### ISSUE TITLE
save file backup

### ISSUE THREAD

**Issue by hualazimo7** [lesserkuma/GBA_MultiMenu#1]
can i backup the save files by gbxcart?

**Comment by Lesserkuma** [comment]
Hi. Generally speaking, yes.

If your cartridge has a battery, you can backup the save data of the last played game with the option "Unlicensed 512K SRAM". This requires at least Version 3.35 of the FlashGBX software.

If your cartridge doesn't have a battery and all your games are patched for "batteryless" SRAM, this will be more difficult. You will have to backup the entire ROM compilation and then extract the individual game ROMs using a hex editor etc. They will have the save data embedded into the ROM file somewhere. There is currently no tool for doing this automatically.

**Comment by hualazimo7** [comment]
Thanks for your reply. My cartridge has a battery indeed, while I used the flashgbx ver.3.29 before this Q&A.   I appreciate your work, thank your again.
