### ISSUE TITLE
Custom background image?

### ISSUE THREAD

**Issue by taylorling** [lesserkuma/GBA_MultiMenu#2]
Thanks for this mini app, it works well to create new multi rom file for the 369in1 - appreciate it a lot!

Do you plan for future update to allow custom background image as long as it follows layout restriction? Also on the different font type, do you mean the font files have to install in Windows? 

Thanks!

**Comment by Lesserkuma** [comment]
Thanks, the feature has been added. It should be an indexed PNG file that has less than 240 colors.
I can't provide the other font files due to copyright. They are:
NTR_IPL_font_s.nftr
TBF1_s.nftr
TBF1-cn_s.nftr
TBF1-kr_s.nftr
TWL-IRAJ-1.nftr
