### ISSUE TITLE
Error: Unsupported cartridge

### ISSUE THREAD

**Issue by kran27** [lesserkuma/GBA_MultiMenu#3]
im trying to make a compilation of videos converted with Meteo, i tried before and after running through gbafix.exe, trying to load them says "Unsupported cartridge". I'm trying to run it in mGBA, made it with cartidge type 4.

**Comment by Lesserkuma** [comment]
Hi! Emulators including mGBA do not support the special mapper that these certain multigame cartridges use. So it will only work on those physical cartridges and can not be tested on an emulator.

**Comment by kran27** [comment]
ah i see, thanks!
